## Working with Arrays

Create a 3 x 6-dimensional array, containing only float values. 

In [24]:
import numpy as np

a = np.array([[0,1.1,2.2,3.3,4.4,5.5],[0,1.1,2.2,3.3,4.4,5.5],[0,1.1,2.2,3.3,4.4,5.5]])
a

array([[0. , 1.1, 2.2, 3.3, 4.4, 5.5],
       [0. , 1.1, 2.2, 3.3, 4.4, 5.5],
       [0. , 1.1, 2.2, 3.3, 4.4, 5.5]])

Check the dimension you have created is correct (use “*.shape*”)

In [25]:
a.shape

(3, 6)

Substitute the 5th element from the 2nd row with 19.75.

In [26]:
a[1,5] = 19.75
a

array([[ 0.  ,  1.1 ,  2.2 ,  3.3 ,  4.4 ,  5.5 ],
       [ 0.  ,  1.1 ,  2.2 ,  3.3 ,  4.4 , 19.75],
       [ 0.  ,  1.1 ,  2.2 ,  3.3 ,  4.4 ,  5.5 ]])

Extract the 2nd and the 3rd row of the array you created. 

In [27]:
a[1]

array([ 0.  ,  1.1 ,  2.2 ,  3.3 ,  4.4 , 19.75])

In [28]:
a[2]

array([0. , 1.1, 2.2, 3.3, 4.4, 5.5])